# Generated by Django 4.2.5 on 2023-09-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_alter_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('E', 'Euro'), ('U', 'Dollar'), ('R', 'Rubles')], default='R', max_length=1),
        ),
    ]
